---
kind: Namespace
apiVersion: v1
metadata:
  name: mariadb-hooks
  labels:
    app: mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: mariadb-hooks
  labels:
    app: mysql
stringData:
  database-name: MYSQL_DATABASE
  database-password: MYSQL_PASSWORD
  database-root-password: MYSQL_ROOT_PASSWORD
  database-user: MYSQL_USER
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mysql")].port}
  name: mysql
  namespace: mariadb-hooks
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    name: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: mariadb-hooks
  labels:
    app: mysql
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "ocs-storagecluster-ceph-rbd"
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: 'true'
  name: mysql
  namespace: mariadb-hooks
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
      annotations:
        pre.hook.backup.velero.io/command: '["/bin/bash", "-c", "mysql -u root -e \"set global read_only=1;flush tables\""]'
        post.hook.backup.velero.io/command: '["/bin/bash", "-c", "mysql -u root -e \"set global read_only=0\""]'
    spec:
      containers:
      - image: registry.redhat.io/rhel8/mariadb-103
        name: mysql
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: mysql
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: mysql
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-root-password
              name: mysql
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          limits:
            memory: 512Mi
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql
