apiVersion: velero.io/v1
kind: Restore
metadata:
  name: backup-mcg-db
  namespace: openshift-adp
spec:
  backupName: backup-mcg-db
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
  restorePVs: true
