apiVersion: velero.io/v1
kind: Backup
metadata:
  name: mysql-persistent-restic
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  includedNamespaces:
  - mysql-persistent-restic
  storageLocation: velero-dpa-1
  ttl: 720h0m0s
