apiVersion: velero.io/v1
kind: Backup
metadata:
  name: mysql-cephfs-restic-backup-10m-files
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  includedNamespaces:
  - mysql-cephfs-restic
  storageLocation: velero-dpa-1
  ttl: 720h0m0s
