apiVersion: velero.io/v1
kind: Backup
metadata:
  name: multiple-pvs1
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  hooks: {}
  includedNamespaces:
  - multiple-pvs
  storageLocation: velero-dpa-1
  ttl: 720h0m0s
