apiVersion: velero.io/v1
kind: Backup
metadata:
  name: mysql-incremental-restic-2
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  includedNamespaces:
  - mysql-incremental-restic
  storageLocation: velero-dpa-1
  ttl: 720h0m0s
