apiVersion: velero.io/v1
kind: Restore
metadata:
  name: mongodb-hooks
  namespace: openshift-adp
spec:
  backupName: mongodb-hooks
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
  restorePVs: true
