apiVersion: velero.io/v1
kind: Backup
metadata:
  name: mongodb-hooks
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  includedNamespaces:
  - mongodb-hooks
  storageLocation: velero-dpa-1
  ttl: 720h0m0s
