apiVersion: velero.io/v1
kind: Backup
metadata:
  name: mysql-sno-restic
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  hooks: {}
  includedNamespaces:
  - mysql-sno-restic
  storageLocation: velero-dpa-1
  ttl: 720h0m0s
