apiVersion: velero.io/v1
kind: Backup
metadata:
  name: mysql-sno-2
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  hooks: {}
  includedNamespaces:
  - mysql-sno
  storageLocation: velero-dpa-1
  ttl: 720h0m0s
