apiVersion: velero.io/v1
kind: Backup
metadata:
  name: oadp-obc-backup
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  hooks: {}
  includedNamespaces:
  - oadp-obc-backup
  storageLocation: velero-dpa-1
  ttl: 720h0m0s
